=== mnechay/exdb/exdb/exercise.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="1">

<!-- An attribute type allowing only certain language codes (currently: DE or EN) -->
<xs:simpleType name="langattr">
    <xs:restriction base="xs:string">
        <xs:enumeration value="DE"/>
        <xs:enumeration value="EN"/>
    </xs:restriction>
</xs:simpleType>

<!-- A type that enforce a "lang" attribute of type "langattr" -->
<xs:complexType name="textype">
    <xs:simpleContent>
        <xs:extension base="xs:string">
            <xs:attribute name="lang" type="langattr" use="required"/>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>

<!-- Type for tags: Tokens that don't contain a comma (which is used to separate tags -->
<xs:simpleType name="tagtype">
    <xs:restriction base="xs:token">
        <xs:pattern value="[^,]+"/>
    </xs:restriction>
</xs:simpleType>

<xs:element name="exercise">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="creator" type="xs:string"/>
            <xs:element name="description" type="xs:string"/>
            <xs:element name="modified" type="xs:dateTime"/>
            <xs:element name="tex_preamble" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="tex_exercise" type="textype" maxOccurs="unbounded"/>
            <xs:element name="tex_solution" type="textype" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="tag" type="tagtype" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="schemaversion" type="xs:integer" use="required"/>
        <xs:attribute name="id" type="xs:integer" use="required"/>
    </xs:complexType>
    <xs:unique name="onlyOneExercisePerLanguage">
        <xs:selector xpath="tex_exercise"/>
        <xs:field    xpath="@lang"/>
    </xs:unique>
    <xs:unique name="onlyOneSolutionPerLanguage">
        <xs:selector xpath="tex_solution"/>
        <xs:field    xpath="@lang"/>
    </xs:unique>
</xs:element>

</xs:schema>

=== mnechay/exdb/test/data/testinstance/repo/exercises/foobar1/foobar1.xml
<?xml version='1.0' encoding='utf-8'?>
<exercise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaversion="2" xsi:noNamespaceSchemaLocation="exercise.xsd">
  <creator>foobar</creator>
  <number>1</number>
  <description>demo exercise</description>
  <modified>2012-05-30T09:36:10</modified>
  <tex_preamble>\usepackage{listings}</tex_preamble>
  <tex_exercise lang="DE">$x$</tex_exercise>
  <tex_solution lang="DE">$y$</tex_solution>
  <tex_solution lang="EN">$z$\lstinputlisting{example.cpp}</tex_solution>
  <data_file>example.cpp</data_file>
  <tag>aabc</tag>
  <tag>Revised Simplex</tag>
</exercise>

=== mnechay/exdb/test/data/testinstance/repo/exercises/jensmander1/jensmander1.xml
<?xml version='1.0' encoding='utf-8'?>
<exercise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaversion="1" xsi:noNamespaceSchemaLocation="exercise.xsd">
  <creator>jensmander</creator>
  <number>1</number>
  <description>Eine Aufgabe</description>
  <modified>2013-04-05T10:10:00</modified>
  <tex_preamble>\usepackage[utf8]{inputenc}</tex_preamble>
  <tex_exercise lang="DE">$x^2$</tex_exercise>
  <tex_exercise lang="EN">$y^3$</tex_exercise>
  <tag>Linear Optimization</tag>
  <tag>Analysis</tag>
</exercise>

=== mnechay/exdb/test/data/jemand1.xml
<?xml version='1.0' encoding='utf-8'?>
<exercise xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" schemaversion="1" xsi:noNamespaceSchemaLocation="exercise.xsd">
  <creator>jemand</creator>
  <number>1</number>
  <description>eine langweilige Aufgabe</description>
  <modified>2002-05-30T09:30:10</modified>
  <tex_preamble>\usepackage[utf8]{inputenc}</tex_preamble>
  <tex_exercise lang="DE">$x$</tex_exercise>
  <tex_solution lang="DE">$y$</tex_solution>
  <tex_solution lang="EN">$z$รถ</tex_solution>
  <tag>aabc</tag>
  <tag>Revised Simplex</tag>
</exercise>
